### ISSUE TITLE
[FRONTEND] Design events page

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/Kabya#5]
While we make a backend API for the events, feel free to design events page.

How?
- /events should take you to event page
- don't add any link on navbar or anything, just add route to App.tsx and work on UI

Feel free to take inspirations from references below but don't copy it. 
References:
![image](https://github.com/KriteshTimsina/Kabya/assets/103115789/58c2cb68-b360-48bc-a583-ffb2925c7b9a)
![image](https://github.com/KriteshTimsina/Kabya/assets/103115789/cfb808d0-d43a-4ace-96a2-f6a0e6ce3498)

**Comment by dilini-liyanage** [comment]
I like to work on this. Can you assign this to me?
